# Generated by Django 3.1.7 on 2021-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhub', '0003_auto_20210309_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('mesg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
